SHOW USER;
--CASO 1: CREACION DE USUARIOS
CREATE USER PRY2205_EFT
IDENTIFIED BY AnalistaProgramador2026
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

CREATE USER PRY2205_EFT_DES
IDENTIFIED BY AnalistaProgramador2026
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

CREATE USER PRY2205_EFT_CON
IDENTIFIED BY AnalistaProgramador2026
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

-- CREACION DE ROLES
CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_C;
GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;


--OTORGAR PRIVILEGIOS DE SISTEMA.

-- PERMISOS PARA PRY2205_EFT

GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, 
CREATE PUBLIC SYNONYM, CREATE SYNONYM, CREATE SESSION 
TO PRY2205_EFT;

-- PERMISOS PARA PRY2205_EFT_DES


GRANT CREATE SEQUENCE, CREATE PROCEDURE, CREATE VIEW, CREATE SESSION 
TO PRY2205_ROL_D;

--GRANT CREATE VIEW TO PRY2205_EFT_DES;

GRANT CREATE PUBLIC SYNONYM TO PRY2205_ROL_D;

-- PERMISOS PARA PRY2205_EFT_CON
GRANT CREATE SESSION TO PRY2205_EFT_CON;


