--- USUARIO PRY2205_EFT_DES

SHOW USER;

-- CASO 2

-- CREACION DE VISTA
CREATE OR REPLACE VIEW VW_ANALISIS_DEUDORES_PERIODO AS
SELECT * FROM SYN_VW_ANALISIS_DEUDORES_PERIODO
WITH READ ONLY;

--CREACION DE SINONIMOS PUBLICOS 
CREATE PUBLIC SYNONYM VW_ANALISIS_DEUDORES_PERIODO 
FOR VW_ANALISIS_DEUDORES_PERIODO;
--OTORGAR PRIVILEGIOS AL USUARIO PRY2205_EFT_CON
GRANT SELECT ON SYN_VW_ANALISIS_DEUDORES_PERIODO TO PRY2205_EFT_CON