---EJERCICIO 1
SELECT c.NOMBRE,
TO_CHAR (c.FECHA_HORA, 'DD/MM/YYYY HH24:MI') AS "FECHA_HORA",
e.NOMBRE|| ' ' || e.APELLIDO_PATERNO|| ' ' || e.APELLIDO_MATERNO AS "NOMBRE ENTRENADOR",
s.NOMBRE || ' ' || s.APELLIDO_PATERNO || ' ' || s.APELLIDO_MATERNO AS "NOMBRE SOCIO"
FROM CLASE_GYM c
INNER JOIN ENTRENADOR e 
ON c.ID_ENTRENADOR = e.ID_ENTRENADOR
INNER JOIN CLASE_INSCRIPCION i
ON i.ID_CLASE = c.ID_CLASE
INNER JOIN SOCIO_GYM s
ON s.ID_SOCIO = i.ID_SOCIO
ORDER BY c.FECHA_HORA;
/

---EJERCICIO 2

SELECT  C.NOMBRE,
e.NOMBRE || ' ' || e.APELLIDO_PATERNO "ENTRENADOR",
c.CUPOS "CUPOS",
NVL(COUNT (i.ID_SOCIO),0) "INSCRIPCIONES",
ROUND(NVL(COUNT(i.ID_SOCIO), 0) / NULLIF (c.CUPOS, 0)
* 100, 2) AS "%_OCUPACION"
FROM CLASE_GYM c
INNER JOIN ENTRENADOR e
ON c.ID_ENTRENADOR = e.ID_ENTRENADOR
LEFT JOIN CLASE_INSCRIPCION i
ON i.ID_CLASE = c.ID_CLASE
GROUP BY c.nombre, e.NOMBRE, e.APELLIDO_PATERNO, c.CUPOS
ORDER BY c.NOMBRE;

---EJERCICIO 3

SELECT
s.NOMBRE || ' ' || s.APELLIDO_PATERNO || ' ' || s.APELLIDO_MATERNO AS 
"NOMBRE SOCIO",
c.NOMBRE AS "NOMBRE_CLASE",
e.NOMBRE || ' ' || e.APELLIDO_PATERNO AS "NOMBRE ENTRENADOR",
    CASE 
        WHEN i.ID_SOCIO is not null then 'INSCRITO'
        ELSE 'SIN INSCRIPCION'
    END AS "ESTADO_INSCRIPCION"
FROM SOCIO_GYM s
INNER JOIN CLASE_INSCRIPCION i ON s.ID_SOCIO = i.ID_SOCIO
RIGHT JOIN CLASE_GYM c ON i.ID_CLASE = c.ID_CLASE
LEFT JOIN ENTRENADOR e ON c.ID_ENTRENADOR = e.ID_ENTRENADOR














